
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ror_db
  pool: 5
  username: root
  password: 124224high

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ror_db
  pool: 5
  username: root
  password: 124224high

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ror_db
  pool: 5
  username: root
  password: 124224high
